const C={primary:'#0073AA',header:'#DDF2FF',card:'#EAF5FC',border:'#D5EAF6',ink:'#1E3443',muted:'#516774',line:'#D5E5EE',good:'#0F7952',goodBg:'#EAF7F0',warn:'#A8500C',warnBg:'#FFF4E5',neutral:'#F0F3F5',white:'#FFFFFF'};
const font='Noto Sans SC';
function frame(p,n,o={}){return Insert(p,{type:'frame',name:n,layout:'vertical',width:'fill_container',height:'fit_content',gap:12,...o});}
function row(p,n,o={}){return frame(p,n,{layout:'horizontal',alignItems:'center',gap:8,...o});}
function text(p,s,size=14,color=C.ink,weight='normal',o={}){const sizing=o.textGrowth==='auto'?{textGrowth:'auto'}:{textGrowth:'fixed-width',width:'fill_container'};return Insert(p,{type:'text',name:s.replace(/\n/g,' / ').slice(0,60),content:s,fontFamily:font,fontSize:size,fontWeight:weight,lineHeight:1.5,fill:color,...sizing,...o});}
function icon(p,n,color=C.primary,size=20){const glyph=n==='clock'||n==='circle-help'?'info':n;return Insert(p,{type:'icon',name:n,library:'lucide',icon:glyph,width:size,height:size,fill:color});}
function actionIcon(p,n){const a=row(p,n+' 操作',{width:48,height:48,justifyContent:'center',cornerRadius:10});icon(a,n);return a;}
function line(p){return Insert(p,{type:'rectangle',name:'分隔线',width:'fill_container',height:1,fill:C.line});}
function button(p,s,kind='primary',ico){const b=row(p,s,{height:50,padding:[10,16],justifyContent:'center',cornerRadius:10,fill:kind==='primary'?C.primary:C.white,stroke:kind==='primary'?C.primary:C.line,strokeWidth:1});if(ico)icon(b,ico,kind==='primary'?C.white:C.primary);text(b,s,15,kind==='primary'?C.white:C.primary,'600',{textGrowth:'auto'});return b;}
function chip(p,s,active=false){const b=row(p,s,{width:'fit_content',height:48,padding:[10,12],cornerRadius:10,fill:active?C.header:C.white,stroke:active?C.primary:C.line,strokeWidth:1});text(b,s,13,active?C.primary:C.muted,active?'600':'normal',{textGrowth:'auto'});return b;}
function note(p,title,body,kind='neutral',ico='info'){const col=kind==='good'?C.good:kind==='warn'?C.warn:C.muted;const bg=kind==='good'?C.goodBg:kind==='warn'?C.warnBg:C.neutral;const n=row(p,title,{alignItems:'start',padding:14,cornerRadius:10,fill:bg,gap:10});icon(n,ico,col,18);const c=frame(n,'提示内容',{gap:4});text(c,title,14,col,'600');if(body)text(c,body,12,col);return n;}
function pill(p,s,kind='good'){const color=kind==='good'?C.good:kind==='warn'?C.warn:C.muted;const b=row(p,s,{width:'fit_content',padding:[4,8],gap:5,cornerRadius:6,fill:kind==='good'?C.goodBg:kind==='warn'?C.warnBg:C.neutral});icon(b,kind==='good'?'circle-check':kind==='warn'?'circle-x':'circle-help',color,14);text(b,s,12,color,'600',{textGrowth:'auto'});}
function navbar(p,active='候补'){const bar=row(p,'底部导航',{padding:[10,16,16,16],gap:8,fill:C.white,stroke:C.line,strokeWidth:{top:1}});for(const [s,ic] of [['查票','train-front'],['候补','ticket'],['想去','star']]){const it=frame(bar,s,{gap:3,alignItems:'center',padding:6,cornerRadius:10,fill:s===active?C.header:C.white,height:58});icon(it,ic,s===active?C.primary:C.muted);text(it,s,12,s===active?C.primary:C.muted,s===active?'600':'normal',{textAlign:'center'});}return bar;}
function start(name,title,sub,index,{back=false,width=390}={}){const s=frame(document,name,{x:(index%4)*454,y:Math.floor(index/4)*1800,width,height:'fit_content(900)',clip:true,placeholder:true,gap:0,fill:C.white,cornerRadius:16});const top=frame(s,'页头',{padding:[12,16,18,16],gap:14,fill:{type:'gradient',gradientType:'linear',rotation:180,colors:[{color:C.header,position:0},{color:C.white,position:1}]}});const status=row(top,'系统状态栏',{height:24});text(status,'9:41',12,C.ink,'600');icon(status,'wifi',C.ink,15);icon(status,'battery-full',C.ink,18);const bar=row(top,'品牌与标题',{height:48});if(back)actionIcon(bar,'chevron-left');else{const brand=row(bar,'品牌图标',{width:30,height:30,justifyContent:'center',cornerRadius:9,fill:C.primary});icon(brand,'train-front',C.white,20);}text(bar,back?title:'有票再出发',18,C.ink,'bold');if(!back)actionIcon(bar,'settings');if(!back)text(top,title,25,C.primary,'bold');if(sub)text(top,sub,13,C.muted);const body=frame(s,'页面内容',{padding:[0,16,20,16],gap:16});screens.push(s);return {s,body};}
function end(s,nav=true){if(nav)navbar(s);const foot=row(s,'系统手势区',{height:24,justifyContent:'center'});Insert(foot,{type:'rectangle',name:'手势条',width:108,height:4,cornerRadius:4,fill:C.ink});Update(s,{placeholder:false});}
function field(p,label,value,ico='chevron-right'){const r=row(p,label,{height:50});text(r,label,14,C.muted);text(r,value,14,C.ink,'600',{textAlign:'right'});icon(r,ico,C.muted,17);}
