const C={primary:'#0073AA',header:'#DDF2FF',card:'#EAF5FC',border:'#D5EAF6',ink:'#1E3443',muted:'#516774',line:'#D5E5EE',good:'#0F7952',goodBg:'#EAF7F0',warn:'#A8500C',warnBg:'#FFF4E5',neutral:'#F0F3F5',white:'#FFFFFF'};
const font='Noto Sans SC';
function frame(p,n,o={}){return Insert(p,{type:'frame',name:n,layout:'vertical',width:'fill_container',height:'fit_content',gap:12,...o});}
function row(p,n,o={}){return frame(p,n,{layout:'horizontal',alignItems:'center',gap:8,...o});}
function text(p,s,size=14,color=C.ink,weight='normal',o={}){return Insert(p,{type:'text',name:s.replace(/\n/g,' / ').slice(0,60),content:s,fontFamily:font,fontSize:size,fontWeight:weight,lineHeight:1.5,fill:color,textGrowth:'fixed-width',width:'fill_container',...o});}
function icon(p,n,color=C.primary,size=20){return Insert(p,{type:'icon',name:n,library:'lucide',icon:n,width:size,height:size,fill:color});}
function actionIcon(p,n){const a=row(p,n+' 操作',{width:48,height:48,justifyContent:'center',cornerRadius:10});icon(a,n);return a;}
function line(p){return Insert(p,{type:'rectangle',name:'分隔线',width:'fill_container',height:1,fill:C.line});}
function button(p,s,kind='primary',ico){const b=row(p,s,{height:50,padding:[10,16],justifyContent:'center',cornerRadius:10,fill:kind==='primary'?C.primary:C.white,stroke:kind==='primary'?C.primary:C.line,strokeWidth:1});if(ico)icon(b,ico,kind==='primary'?C.white:C.primary);text(b,s,15,kind==='primary'?C.white:C.primary,'600',{textGrowth:'auto'});return b;}
function chip(p,s,active=false){const b=row(p,s,{width:'fit_content',height:48,padding:[10,12],cornerRadius:10,fill:active?C.header:C.white,stroke:active?C.primary:C.line,strokeWidth:1});text(b,s,13,active?C.primary:C.muted,active?'600':'normal',{textGrowth:'auto'});return b;}
function note(p,title,body,kind='neutral',ico='info'){const col=kind==='good'?C.good:kind==='warn'?C.warn:C.muted;const bg=kind==='good'?C.goodBg:kind==='warn'?C.warnBg:C.neutral;const n=row(p,title,{alignItems:'start',padding:14,cornerRadius:10,fill:bg,gap:10});icon(n,ico,col,18);const c=frame(n,'提示内容',{gap:4});text(c,title,14,col,'600');if(body)text(c,body,12,col);return n;}
function pill(p,s,kind='good'){const color=kind==='good'?C.good:kind==='warn'?C.warn:C.muted;const b=row(p,s,{width:'fit_content',padding:[4,8],gap:5,cornerRadius:6,fill:kind==='good'?C.goodBg:kind==='warn'?C.warnBg:C.neutral});icon(b,kind==='good'?'circle-check':kind==='warn'?'circle-x':'circle-help',color,14);text(b,s,12,color,'600',{textGrowth:'auto'});}
function navbar(p,active='候补'){const bar=row(p,'底部导航',{padding:[10,16,16,16],gap:8,fill:C.white,stroke:C.line,strokeWidth:{top:1}});for(const [s,ic] of [['查票','train-front'],['候补','scan-line'],['想去','star']]){const it=frame(bar,s,{gap:3,alignItems:'center',padding:6,cornerRadius:10,fill:s===active?C.header:C.white,height:58});icon(it,ic,s===active?C.primary:C.muted);text(it,s,12,s===active?C.primary:C.muted,s===active?'600':'normal',{textAlign:'center'});}return bar;}
function start(name,title,sub,index,{back=false,width=390}={}){const s=frame(document,name,{x:(index%4)*454,y:Math.floor(index/4)*1800,width,height:'fit_content(900)',clip:true,placeholder:true,gap:0,fill:C.white,cornerRadius:16});const top=frame(s,'页头',{padding:[12,16,18,16],gap:14,fill:{type:'gradient',gradientType:'linear',rotation:180,colors:[{color:C.header,position:0},{color:C.white,position:1}]}});const status=row(top,'系统状态栏',{height:24});text(status,'9:41',12,C.ink,'600');icon(status,'wifi',C.ink,15);icon(status,'battery-full',C.ink,18);const bar=row(top,'品牌与标题',{height:48});if(back)actionIcon(bar,'chevron-left');else{const brand=row(bar,'品牌图标',{width:30,height:30,justifyContent:'center',cornerRadius:9,fill:C.primary});icon(brand,'train-front',C.white,20);}text(bar,back?title:'有票再出发',18,C.ink,'bold');if(!back)actionIcon(bar,'settings');if(!back)text(top,title,25,C.primary,'bold');if(sub)text(top,sub,13,C.muted);const body=frame(s,'页面内容',{padding:[0,16,20,16],gap:16});screens.push(s);return {s,body};}
function end(s,nav=true){if(nav)navbar(s);const foot=row(s,'系统手势区',{height:24,justifyContent:'center'});Insert(foot,{type:'rectangle',name:'手势条',width:108,height:4,cornerRadius:4,fill:C.ink});Update(s,{placeholder:false});}
function field(p,label,value,ico='chevron-right'){const r=row(p,label,{height:50});text(r,label,14,C.muted);text(r,value,14,C.ink,'600',{textAlign:'right'});icon(r,ico,C.muted,17);}
function number(p,count=2){const c=frame(p,'候补人数设置',{gap:10});const r=row(c,'候补人数标题');text(r,'候补人数',15,C.ink,'600');text(r,'按同一席别校验',12,C.muted,'normal',{textAlign:'right'});const nr=row(c,'人数输入',{gap:12});for(const label of ['−',String(count),'+']){const f=row(nr,label==='−'?'减少人数':label==='+'?'增加人数':'输入人数',{width:label===String(count)?'fill_container':52,height:52,justifyContent:'center',cornerRadius:10,fill:C.white,stroke:C.line,strokeWidth:1});text(f,label,24,label===String(count)?C.ink:C.primary,'600',{textGrowth:'auto'});}text(c,'填写本次一起候补的人数',12,C.muted);}
function summary(p,count=2){const r=row(p,'查询条件摘要',{padding:[12,14],cornerRadius:10,fill:C.card});const c=frame(r,'条件',{gap:2});text(c,'北京南 → 济南西',16,C.ink,'600');text(c,`10月1日 · 二等座 · ${count} 人`,13,C.muted);actionIcon(r,'sliders-horizontal');}
function metrics(p,values){const r=row(p,'结果概览',{gap:8});for(const [v,label,kind] of values){const c=frame(r,label,{padding:[12,8],alignItems:'center',gap:2,cornerRadius:10,fill:kind==='good'?C.goodBg:kind==='warn'?C.warnBg:C.neutral});text(c,v,25,kind==='good'?C.good:kind==='warn'?C.warn:C.muted,'bold',{textAlign:'center'});text(c,label,12,kind==='good'?C.good:kind==='warn'?C.warn:C.muted,'normal',{textAlign:'center'});}}
function train(p,{code='G101',depart='07:00',arrive='08:38',kind='good',status='本次校验通过',reason='本次 2 人提交条件校验通过',at='09:41:08',selected=false,people=2}={}){const c=frame(p,`${code} 二等座 ${people}人 ${status}`,{padding:14,gap:12,cornerRadius:12,fill:C.card,stroke:selected?C.primary:C.border,strokeWidth:selected?2:1});const h=row(c,'车次与状态');text(h,code,18,C.ink,'bold');pill(h,status,kind);const t=row(c,'行程时刻',{justifyContent:'space_between'});const a=frame(t,'出发',{gap:0});text(a,depart,26,C.ink,'600');text(a,'北京南',13,C.muted);const mid=frame(t,'车程',{gap:4,alignItems:'center'});text(mid,'1小时38分',12,C.muted,'normal',{textAlign:'center'});line(mid);text(mid,'当日到达',12,C.muted,'normal',{textAlign:'center'});const b=frame(t,'到达',{gap:0});text(b,arrive,26,C.ink,'600',{textAlign:'right'});text(b,'济南西',13,C.muted,'normal',{textAlign:'right'});line(c);const info=row(c,'席别与人数');text(info,`10月1日 · 二等座 · ${people} 人`,13,C.ink);icon(info,'chevron-right',C.primary,18);text(c,reason,13,kind==='good'?C.good:kind==='warn'?C.warn:C.muted);text(c,`${at} 校验`,12,C.muted);return c;}
screens=[];
{
const {s,body}=start('01 填写候补条件','先探测，再去候补','按人数查看，哪些车次当前可以提交',0);
const route=frame(body,'行程条件',{padding:16,gap:10,cornerRadius:12,fill:C.card,stroke:C.border,strokeWidth:1});const r=row(route,'出发与到达');const a=frame(r,'出发',{gap:3});text(a,'出发地',12,C.muted);text(a,'北京',26,C.ink,'600');text(a,'同城各站',12,C.muted);icon(r,'arrow-right',C.primary,22);const b=frame(r,'目的地',{gap:3});text(b,'目的地',12,C.muted,'normal',{textAlign:'right'});text(b,'济南',26,C.ink,'600',{textAlign:'right'});text(b,'同城各站',12,C.muted,'normal',{textAlign:'right'});line(route);field(route,'出发日期','10月1日  星期四');line(route);field(route,'出发时段','全天');
const f=frame(body,'人数与席别',{padding:16,gap:14,cornerRadius:12,fill:C.card,stroke:C.border,strokeWidth:1});number(f);line(f);text(f,'候补席别',15,C.ink,'600');const chips=row(f,'席别选择');chip(chips,'二等座',true);chip(chips,'一等座');chip(chips,'更多席别');text(f,'多个席别分别探测，人数不跨席别合计',12,C.muted);button(body,'开始探测','primary','scan-line');text(body,'仅检查提交条件；正式候补在 12306 App 完成。',12,C.muted);end(s);
}
{
const {s,body}=start('02 正在探测','正在探测候补','人数和席别已固定，可随时停止',1,{back:true});summary(body);const p=frame(body,'探测进度',{padding:18,gap:14,cornerRadius:12,fill:C.card});const r=row(p,'进度标题');text(r,'正在校验提交条件',17,C.ink,'600');text(r,'2 / 3 项',14,C.primary,'600',{textAlign:'right'});const bar=frame(p,'进度条',{layout:'none',height:6,cornerRadius:3,fill:C.border});Insert(bar,{type:'rectangle',name:'已完成2/3',x:0,y:0,width:204,height:6,cornerRadius:3,fill:C.primary});text(p,'正在校验 G105 · 二等座 · 2 人',13,C.muted);text(p,'每个车次和席别单独计为 1 项',12,C.muted);metrics(body,[['1','校验通过','good'],['1','不可提交','warn'],['0','未确认','neutral']]);text(body,'已完成的结果',16,C.ink,'600');train(body);note(body,'剩余 1 项尚未完成','停止后保留已完成结果，可继续剩余项目。','neutral','clock');button(body,'停止探测','secondary');end(s,false);
}
{
const {s,body}=start('03 探测结果','候补探测结果','按本次人数查看结果，再选择车次',2,{back:true});summary(body);metrics(body,[['1','校验通过','good'],['1','不可提交','warn'],['1','未确认','neutral']]);const filters=row(body,'结果筛选',{gap:6});chip(filters,'全部',true);chip(filters,'通过');chip(filters,'不可提交');chip(filters,'未确认');text(body,'共 3 项 · 09:41 更新 · 通过优先',12,C.muted);train(body,{selected:true});train(body,{code:'G103',depart:'07:20',arrive:'08:58',kind:'warn',status:'当前不可提交',reason:'所选车次候补人数过多',at:'09:41:12'});train(body,{code:'G105',depart:'07:40',arrive:'09:18',kind:'neutral',status:'暂时无法确认',reason:'请求超时，可单独重试',at:'09:41:15'});button(body,'重试未确认的 1 项','secondary','rotate-cw');text(body,'结果随时变化；校验通过不代表候补兑现。',12,C.muted);end(s);
}
{
const {s,body}=start('04 通过详情','候补校验详情','G101 · 北京南 → 济南西',3,{back:true});note(body,'本次校验通过','按 2 人、二等座校验，当前提交条件通过。','good','circle-check');train(body,{status:'2 人通过',reason:'此结果只适用于下方条件',at:'09:41:08'});const c=frame(body,'本次校验条件',{gap:0});field(c,'出发日期','2026年10月1日','calendar-days');line(c);field(c,'候补人数','2 人','users');line(c);field(c,'候补席别','二等座','armchair');line(c);field(c,'校验时间','今天 09:41:08','clock');note(body,'接下来，在 12306 完成候补','仍需选择乘客并提交订单。校验通过不代表已创建订单，也不代表能够兑现。');button(body,'打开 12306 App','primary','external-link');text(body,'打开前重新校验；状态变化时先更新结果。',12,C.muted);button(body,'返回查看其他车次','secondary');end(s,false);
}
{
const {s,body}=start('05 不可提交详情','当前不可提交','G103 · 北京南 → 济南西',4,{back:true});note(body,'所选车次候补人数过多','本次按 2 人、二等座校验，12306 返回了明确拒绝。','warn','circle-x');train(body,{code:'G103',depart:'07:20',arrive:'08:58',kind:'warn',status:'当前不可提交',reason:'所选车次候补人数过多',at:'09:41:12'});text(body,'可以这样继续',18,C.ink,'600');const options=frame(body,'后续操作',{gap:0});field(options,'查看同区间其他车次','选择车次');line(options);field(options,'尝试其他席别','修改席别');note(body,'候补状态可能变化','页面显示支持候补，不等于按当前人数能够提交。需要时可以重新探测。');button(body,'查看校验通过的车次','primary');button(body,'重新探测此车次','secondary','rotate-cw');end(s,false);
}
{
const {s,body}=start('06 未确认与暂停','探测已暂停','已完成的结果已保留',5,{back:true});summary(body);note(body,'需要完成 12306 验证','服务要求验证后才能继续；尚未完成的项目暂时无法确认。','warn','shield-check');metrics(body,[['1','校验通过','good'],['0','不可提交','warn'],['2','未确认','neutral']]);const q=frame(body,'未确认项目',{gap:0});field(q,'G105 · 二等座','需要验证','shield-check');line(q);field(q,'G109 · 二等座','尚未完成','clock');text(body,'未确认不代表候补已满',17,C.ink,'600');text(body,'完成验证后，只重试未完成的项目。已有通过结果仍需检查是否过期。',14,C.muted);button(body,'前往完成验证','primary','shield-check');button(body,'先查看已有结果','secondary');end(s,false);
}
{
const {s,body}=start('07 人数变化与结果失效','人数已变更','请按新人数重新探测',6,{back:true});summary(body,3);note(body,'原结果按 2 人校验','现在选择了 3 人，旧结果已失效，不能用于本次判断。','neutral','refresh-cw');const n=frame(body,'新候补人数',{padding:16,gap:14,cornerRadius:12,fill:C.card});number(n,3);text(body,'上次记录 · 仅供参考',16,C.muted,'600');train(body,{kind:'neutral',status:'需要重新探测',people:2,reason:'旧记录：2 人 · 09:41 校验，不适用于 3 人'});button(body,'按 3 人重新探测','primary','scan-line');text(body,'更改日期、区间或席别后，同样需要重新探测。',12,C.muted);end(s,false);
}
{
const {s,body}=start('08 空结果与异常边界','没有可提交的结果','已完成本次全部候选项目的校验',7,{back:true});summary(body);metrics(body,[['0','校验通过','good'],['3','不可提交','warn'],['0','未确认','neutral']]);const empty=frame(body,'零通过状态',{padding:[28,12],alignItems:'center',gap:12});icon(empty,'calendar-search',C.primary,44);text(empty,'试试其他日期或席别',21,C.ink,'600',{textAlign:'center'});text(empty,'本次 3 项均收到明确拒绝。\n可以调整条件，再找合适的车次。',14,C.muted,'normal',{textAlign:'center'});button(body,'调整条件重新探测','primary');button(body,'查看 3 项拒绝原因','secondary');note(body,'想先看看现票？','回到查票，看看其他城市有没有余票。','neutral','train-front');end(s);
}
Print('screens',screens);
